name: Release corona

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14

      - name: Build application
        run: make build

      - name: Calculate version
        run: echo "CORONA_VERSION=v$(git log --oneline --all | wc -l)" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CORONA_VERSION }}
          release_name: ${{ env.CORONA_VERSION }}
          draft: false
          prerelease: false

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/corona
          asset_name: corona
          asset_content_type: application/octet-stream
